<?php

namespace Datto\RemoteManagement;

use Datto\Service\Networking\NetworkService;
use Datto\Common\Utility\Filesystem;
use Datto\Log\DeviceLoggerInterface;

/**
 * Handles configuring salt-minion with any device-specific configurations.
 *
 * This is needed because SYSENG uses the short hostname as their naming convention rather than FQDN (dumb). Rather than
 * changing it on them now, we can revisit this in the future.
 *
 * TODO: consider consolidating with other configuration classes.
 *
 * @author Chad Kosie <ckosie@datto.com>
 */
class SaltMinion
{
    const SERVICE_NAME = 'salt-minion.service';
    const ID_CONFIGURATION_FILE = '/etc/salt/minion.d/10-datto-id.conf';
    const ID_CONFIGURATION_FORMAT = <<<EOF
# Configuration file generated by systemd datto-salt-configure.service

id: %s

EOF;

    /** @var DeviceLoggerInterface */
    private $logger;

    /** @var Filesystem */
    private $filesystem;

    /** @var NetworkService */
    private $networkService;

    /**
     * @param DeviceLoggerInterface $logger
     * @param Filesystem $filesystem
     * @param NetworkService $networkService
     */
    public function __construct(
        DeviceLoggerInterface $logger,
        Filesystem $filesystem,
        NetworkService $networkService
    ) {
        $this->logger = $logger;
        $this->filesystem = $filesystem;
        $this->networkService = $networkService;
    }

    /**
     * Update salt's configuration.
     */
    public function configure()
    {
        $this->logger->info("SMS0001 Checking to see if salt minion needs configuration update ...");

        $existingConfiguration = $this->getExistingConfiguration();
        $generatedConfiguration = $this->getGeneratedConfiguration();

        if ($existingConfiguration !== $generatedConfiguration) {
            $this->logger->info("SMS0004 Salt minion configuration update needed, updating ...");
            $this->writeConfiguration($generatedConfiguration);
            $this->logger->info("SMS0005 Salt minion configuration update complete");
        } else {
            $this->logger->info("SMS0003 Salt minion configuration update not needed");
        }

        $this->logger->info("SMS0002 Salt minion configuration check complete");
    }

    /**
     * @param string $configuration
     */
    private function writeConfiguration(string $configuration)
    {
        $this->filesystem->filePutContents(self::ID_CONFIGURATION_FILE, $configuration);
    }

    /**
     * @return string
     */
    private function getGeneratedConfiguration(): string
    {
        return sprintf(
            self::ID_CONFIGURATION_FORMAT,
            $this->networkService->getShortHostname()
        );
    }

    /**
     * Get configuration contents.
     *
     * @return string|null
     */
    private function getExistingConfiguration()
    {
        if (!$this->filesystem->exists(self::ID_CONFIGURATION_FILE)) {
            return null;
        }

        return $this->filesystem->fileGetContents(self::ID_CONFIGURATION_FILE);
    }
}
